class Control {
  constructor(csv1, csv2) {
    
      const mapBar = d3.select('.map-container');
      const textBox = d3.select('.textbox')

      const color = d3.scaleOrdinal()
      .domain([
        "Data DevOps Engineer",
        "Data Architect",
        "Data Scientist",
        "Machine Learning Researcher",
        "Data Engineer",
        "Machine Learning Engineer",
        "Data Analyst",
        "Analytics Engineer",
        "Applied Scientist",
        "BI Developer",
        "Business Intelligence Engineer",
        "Research Scientist",
        "Research Analyst",
        "Research Engineer",
        "Data Science Engineer",
        "Data Quality Analyst",
        "Data Product Manager",
        "Machine Learning Scientist",
        "AI Engineer",
        "MLOps Engineer",
        "Deep Learning Engineer",
        "Data Modeler",
        "Data Product Owner",
        "Data Science Consultant",
        "Business Intelligence Analyst",
        "AI Developer",
        "Data Manager",
        "ML Engineer",
        "Data Science Director",
        "Head of Data",
        "BI Analyst",
        "Data Management Analyst",
        "Machine Learning Modeler",
        "Data Specialist",
        "BI Data Analyst",
        "Data Integration Engineer",
        "Business Intelligence Manager",
        "Data Integration Specialist",
        "Data Science Practitioner",
        "Business Intelligence Developer",
        "AI Research Engineer",
        "Data Lead",
        "Data Management Specialist",
        "AI Architect",
        "Data Science Manager",
        "Data Strategist",
        "Business Intelligence Specialist",
        "Machine Learning Infrastructure Engineer",
        "Data Quality Engineer",
        "Director of Data Science",
        "Business Data Analyst",
        "Decision Scientist",
        "Financial Data Analyst",
        "Data Strategy Manager",
        "Computer Vision Engineer",
        "Data Visualization Specialist",
        "Insight Analyst",
        "Data Visualization Engineer",
        "ETL Developer",
        "Data Analytics Manager",
        "Azure Data Engineer",
        "Data Developer",
        "Principal Data Scientist",
        "Data Science Lead",
        "Staff Data Analyst",
        "Data Infrastructure Engineer",
        "Machine Learning Software Engineer",
        "Machine Learning Operations Engineer",
        "AI Scientist",
        "Head of Machine Learning",
        "Applied Data Scientist",
        "AI Programmer",
        "Data Operations Analyst",
        "Applied Machine Learning Scientist",
        "Data Analytics Lead",
        "Data Operations Engineer",
        "Machine Learning Manager",
        "Lead Data Scientist",
        "Principal Machine Learning Engineer",
        "Principal Data Engineer",
        "Power BI Developer",
        "Head of Data Science",
        "Staff Machine Learning Engineer",
        "Staff Data Scientist",
        "Consultant Data Engineer",
        "Machine Learning Specialist",
        "Business Intelligence Data Analyst",
        "Data Operations Manager",
        "Lead Machine Learning Engineer",
        "Managing Director Data Science",
        "Data Modeller",
        "Finance Data Analyst",
        "Software Data Engineer",
        "Machine Learning Research Engineer",
        "Compliance Data Analyst",
        "Data Operations Specialist",
        "Cloud Data Engineer",
        "Analytics Engineering Manager",
        "NLP Engineer",
        "AWS Data Architect",
        "Product Data Analyst",
        "Machine Learning Developer",
        "Data Visualization Analyst",
        "Autonomous Vehicle Technician",
        "Sales Data Analyst",
        "Applied Machine Learning Engineer",
        "ETL Engineer",
        "Big Data Engineer",
        "Lead Data Analyst",
        "BI Data Engineer",
        "Cloud Database Engineer",
        "Deep Learning Researcher",
        "Data Analytics Specialist",
        "Big Data Architect",
        "Computer Vision Software Engineer",
        "Marketing Data Engineer",
        "Manager Data Management",
        "Data Analytics Consultant",
        "Data Science Tech Lead",
        "Data Scientist Lead",
        "Marketing Data Analyst",
        "Data Analytics Engineer",
        "Cloud Data Architect",
        "Lead Data Engineer",
        "Principal Data Analyst"
        ])
      .range([
        "#b43cae",
        "#0afe7b",
        "#168035",
        "#f53b58",
        "#b0f707",
        "#95d7f1",
        "#7e2e6e",
        "#5d661d",
        "#8618c8",
        "#e6bc51",
        "#c1a1b6",
        "#1e21d6",
        "#4a2fb4",
        "#a51377",
        "#584781",
        "#bfd53d",
        "#f733a9",
        "#89e0ee",
        "#41af24",
        "#fc54f7",
        "#48bba1",
        "#f407f9",
        "#b6f8a1",
        "#565dc1",
        "#dc5429",
        "#0625f1",
        "#c69577",
        "#e21945",
        "#b69764",
        "#ee2ac0",
        "#7f9c5b",
        "#5814bd",
        "#1d339a",
        "#0fe2ea",
        "#c7c640",
        "#399997",
        "#47b621",
        "#0070b8",
        "#c313ce",
        "#856036",
        "#0defae",
        "#c27a69",
        "#e92991",
        "#70380a",
        "#c8a417",
        "#a8d37b",
        "#e4a060",
        "#11effa",
        "#f15d6d",
        "#e9db31",
        "#939f76",
        "#95c5a7",
        "#ea40ae",
        "#78187d",
        "#5c041b",
        "#4b5c1c",
        "#2f3318",
        "#064f4e",
        "#c91404",  
        "#784b74",
        "#19901f",
        "#2dcac2",
        "#9ed3ca",
        "#8b96e3",
        "#58f998",
        "#ef3bf7",
        "#cf69f0",
        "#b0de58",
        "#0a805e",
        "#3336a0",
        "#c3aa0f",
        "#d95fa5",
        "#656e76",
        "#4f14c9",
        "#fdfdea",
        "#b0463f",
        "#df4928",
        "#112880",
        "#1ea71f",
        "#9fb792",
        "#124aef",
        "#c20bef",
        "#94e289",
        "#1b2d66",
        "#1bf3b1",
        "#300c3a",
        "#22ef3f",
        "#4fbd6a",
        "#0c5932",
        "#2b31ca",
        "#384364",
        "#8e95e0",
        "#d1ab77",
        "#4c39ad",
        "#4d995f",
        "#0c9e14",
        "#a43a05",
        "#930223",
        "#59b930",
        "#86ed04",
        "#662737",
        "#622698",
        "#580152",
        "#69fb36",
        "#5c99fa",
        "#8df638",
        "#f514c9",
        "#b7f4c4",
        "#f6be3e",
        "#ce971c",
        "#8f569e",
        "#819dba",
        "#133c06",
        "#3b9cb3",
        "#74dbd8",
        "#74345c",
        "#d88b4e",
        "#eee41b",
        "#f1d556",
        "#9cfa82",
        "#4b0b24",
        "#12e881",
        "#17a15e",
        "#834a40",
        "#5391a7",
        "#d7b9e9"])  

      this.LineGraph = new LineGraph(this, csv2, mapBar, color);
      this.BarChart = new BarChart('.bar-chart-container', csv1);
      this.DisplayName = new DisplayName(this, textBox);

   }

  Test(str) {
      console.log(str);
  }

  Opt(job_title) {
      this.DisplayName.updateText(job_title);
  }

  
}
